### PR TITLE
Wire up party import to UI

### PR DESCRIPTION
**Pull request by mcw0933**

### CODE REVIEW

**Comment by mcw0933** [comment]
Here it is.  :)  Let me know what you think, especially as regards the interaction between the UI ("view model") classes and the import ("model") classes.

There are some lingering questions like - what if you already have a character definition started, prompt the user before overwriting?  What if the character race/role/name/level match?  What if all but the level match?  etc. etc.

Level was peculiar in that the spinner has a ReadOnly property... so you can't programatically, um, spin it?  Or maybe that's just my JavaFX cluelessness.  :)

**Comment by mcw0933** [comment]
Oh, also - I still haven't quite got my NetBeans Java formatting options to match yours, so sorry about the whitespace differences.  Can you export those over to me, or even maybe add them to the repo, so that anyone working can use the same settings?

**Comment by RyanHilbert** [comment]
Most of it looks good so far! From a quick test, it looks like pasting
works half of the time, but the other half of the time it imports only the
name and class of each character and removes all equipment. For the level
spinner, it looks like you need to use the increment/decrement methods to
set it programatically. A prompt to avoid overwriting unsaved builds may be
a good idea, but would probably also be annoying without a 'clear' button.

As for formatting options, I actually just use the default. The problem is
I ignore them most of the time and have a bad habit of condensing code
until it's unreadable. Feel free to reformat (or generally change) any code
you feel the need to. The PartyView code is particularly ugly due to it
being written without concern for others and containing way too many nested
classes. I may look into making a set of formatting options later, provided
they can be easily applied to the entire project afterwards (hopefully via
the 'Right-Click > Format' NetBeans option). I was playing around with them
a few days ago and got particularly excited when I realized there was an
option to NOT turn all of my tabs into spaces.

**Comment by mcw0933** [comment]
Hmm - curious to see the paste that's failing?  I ran two parties, back to back, and was able to see both parties fully represented, all equipment, when I took each CharPane back and forth between the respective class tabs.  Try out the party in the [party1.bbcode](https://raw.githubusercontent.com/Xayrn/CardHunterUtils/master/test/data/party1.bbcode) file - that one works for me.  Maybe add your problematic party as another test data file, might be useful for other testing later.

Increment/decrement - makes sense from a UI standpoint.  I'll see what I can do to manage that.  

Applying the options to the entire project isn't terrible: if you go to NetBeans > Tools > Options > On Save you can configure whether it does an automatic reformat or not.  Then you'd just have to open/save every file in NB.  (Or slowly get there commit by commit, also...)  

Finally - you like tabs?  We can't be friends.  4 space master race.  j/k :>  But yeah, if you want to export your NetBeans options (just the relevant ones) and send over / commit the file that would help a ton.

**Comment by mcw0933** [comment]
Oh, also - so the UI structure presents another interesting question from an export standpoint - do we export just the visible characters, or all "defined" ones (anything with any non-default data), or all nine, period?

**Comment by RyanHilbert** [comment]
Just the visible characters should be exported. Honestly, a tab structure
probably isn't even the best way to represent class choices, since it
implies the characters in other tabs still 'exist' in some form. May be
something to change in the future (spinners or combo boxes for class/race
instead may not be a terrible idea). In the future we can provide a way to
save individual characters and parties of two, but I wouldn't consider it a
priority.

As for the pasting, it looks like pasting twice consecutively causes
issues, regardless of what you do in-between. This is happening with both
my multiplayer party and the one in the file you linked. Every
even-numbered paste seems to behave strangely for me.

**Comment by mcw0933** [comment]
Are your parties overlapping on a role for a character slot?  I'm wondering if "cleaning out" the current slots prior to import is something I need to do.  I assumed the item replace would just work, but maybe not.  The two parties I tested were War-War-War and then Wiz-Pri-Wiz so perhaps I'm not seeing an issue because there's no intersection.

**Comment by RyanHilbert** [comment]
My multiplayer party is two warriors and a priest, and the one you linked
me was two wizards and a priest. I don't think that's the issue, but I
can't debug it right now.

I'd also assume simply replacing the items would work, and for me it does,
but only every other time. It's a really strange quirk. I'd send you some
screenshots if I could load up the program right now.

**Comment by mcw0933** [comment]
Can't debug because you're in the middle of some work?  Or is the build broken or something?

If you paste me the party bbcode you're using I'll try it on my end.  It might be an items issue, maybe the items on your dudes are edge cases that are failing the item.byName lookup?  But that would be consistent each time...

**Comment by RyanHilbert** [comment]
The first one. I usually work at night.

Here's my multiplayer party's code, but it seemed to be happening no matter
what deck I used:

[SIZE=5][B]HACK[/B][/SIZE]
[I]Level 1 [wiki]Elf[/wiki] [wiki]Warrior[/wiki][/I]
[INDENT=1][item]Double-edged Sword[/item]
[item]Double-edged Sword[/item]
[item]Double-edged Sword[/item]
[item]Dependable Mail[/item]
[item]Twisting Shield[/item]
[item]Bubble Helmet[/item]
[item]Shielding Warp Boots[/item]
[item]Cautious Mobility[/item]
[item]Novice Impaling[/item]
[/INDENT]

[SIZE=5][B]BASH[/B][/SIZE]
[I]Level 1 [wiki]Human[/wiki] [wiki]Priest[/wiki][/I]
[INDENT=1][item]Vampire's Blade[/item]
[item]Vampire's Blade[/item]
[item]Fragile Shielded Mail[/item]
[item]Aegis of the Defender[/item]
[item]Shielding Warp Boots[/item]
[item]Incense of Roiled Air[/item]
[item]Amulet of Inspiration[/item]
[item]Amulet of Inspiration[/item]
[item]Advanced Flexibility[/item]
[item]Focused Healer[/item]
[/INDENT]

[SIZE=5][B]CHOP[/B][/SIZE]
[I]Level 1 [wiki]Elf[/wiki] [wiki]Warrior[/wiki][/I]
[INDENT=1][item]Double-edged Sword[/item]
[item]Double-edged Sword[/item]
[item]Double-edged Sword[/item]
[item]Dependable Mail[/item]
[item]Twisting Shield[/item]
[item]Bubble Helmet[/item]
[item]Shielding Warp Boots[/item]
[item]Cautious Mobility[/item]
[item]Novice Impaling[/item]
[/INDENT]

**Pull request merged**
