### PR TITLE
Create Character class to model Card Hunter characters

### PR DESCRIPTION
**Pull request by mcw0933**
```
Add a method for constructing one from a BBCode string
Define a class that models a specific equipment buildout for a character
```

### CODE REVIEW

**Comment by mcw0933** [comment]
Hey - this is the start of the work I'm doing on party import.

The high level plan is this:

Define a model class, Character, that is all the character state info.  I want to have an additional class, Build, that represents a "specific equipment set" for a character.  One feature I think the utility should have is named "builds" so you can rapidly load/compare different equipment sets.  

For now though, Build is just a bag of items.  Eventually I see it encapsulating the validations for level, tokens, race/class, etc.  I think that's kinda being served now by Slot, which is cool, but I think if we go one level further then we don't have to pass Slot varargs/arrays around everywhere.

Anyway, that was just a digression so I could write the Character.fromBBCode static method.  Right now it just takes the Name from the input, but I'll be boosting that, obviously.

One other side thing I did was move the image fetch logic into a helper.  I noticed Item (and probably Card too, but I didn't check) had pretty much the same logic I'd need for figures / character images, so rather than duplicate code I methodized it.

One final note: I'm having trouble with your newer changes to the main method / PartyView.  It blows up with a TargetInvocationException when it tries to initialize the warrior Char variable.  I can get it to build locally if I revert to the old PartyView and comment out the .onSlotClick line from app start.

Anyway, take a look at this, let me know how you feel about my design approach.  Not sure how Character and Char/CharPane might interact down the road but ideally those latter could be view classes that just bind more or less right against Character.

**Comment by RyanHilbert** [comment]
I like the theoretical simplicity of each class. It's important to consider
how this is all going to interact with the user interface, though. I was
building the state right into javafx.scene.Node subclasses because that
seemed like the simplest approach. For example, it looks like you're making
your new classes immutable, which is generally a good thing, but one of the
core paradigms of JavaFX is using mutable properties to monitor changes to
values so that the interface can update its view of them. There may be a
way to get the two concepts to work well together, but being so new to
JavaFX myself, I'm not sure what it would be.

As for the exception you're seeing, it looks like you got rid of a hack I
used to initialize the default Items for each Item.Slot when you methodized
the asset loading code. Add this line near the end of the Item constructor
and you should see the bug go away:
if(image.contains("Default Item"))slot.dfault=this;
The problem is that each Item.Slot is an Enum, but all of the Items are
initialized at run-time, so the default Item values for each Slot had to be
initialized at run-time, too. Moving that loading code into a method was
definitely a good idea, though. I'll probably flesh-out the AssetLoader
class a bit more and make the rest of the code utilize it when I'm less
exhausted.

All in all, I like the ideas; we just need to reconcile them with JavaFX.
Designing the model to fit the view certainly sounds backwards; I'm just
not sure how else to go about it.

**Comment by mcw0933** [comment]
Ah, cool.  Yup, that was the fix.  I missed that in the diff!

As for Character, immutability wasn't totally a concern, actually.  I just got started there by looking at the design for Item and CSV.  I was kinda surprised when I got further in and tripped over Char/CharPane.  But what you're saying makes sense.  JavaFX, if I understand it, is a lot like Microsoft WPF, which I have some familiarity with.  I'm guessing they're going for the "Model-View-ViewModel" (MVVM) style, where you have the ViewModel classes (like Char) with the observables / two-way-binding properties on them, and then you transform those to/from your base, pure object model (Character) on load/save.  http://stackoverflow.com/questions/4061440/asp-net-mvc-model-vs-viewmodel

If that approach is cool with you, it's cool with me, because the nice thing about pure model classes is they don't carry baggage like JavaFX.image and ObservableList down into the model tier for the import/export code to have to deal with.  Right now I have to launch the full app in my test initializations to get JavaFX to load so that Images are processable.  :)  

Speaking of which - what IDE / dev environment are you using?  I'm NetBeans on PC/OSX (two machines).  Not sure how other IDEs handle test classes so I was holding off on adding them to the repo.

**Comment by mcw0933** [comment]
Also, one other thing.  I'm having issues with the test for the Item importer.  I put Item.byName(String) as a static method on Item, and that's working great with the bbCode parser.  

Where it's not working though is off a literal in the test class.  It seems that the regex matcher / CSV importer both construct strings with escaped apostrophes for items like Militiaman's Pike.  I'd rather not have to remember to escape apostrophes if I'm calling it from a test or with a specific item name (e.g. user does an item search or something)

I ran across this: http://stackoverflow.com/questions/3537706/howto-unescape-a-java-string-literal-in-java and now I'm just baffled that there isn't an easier way to handle this in Java.  Not sure if you have any opinions here?

**Pull request merged**
