### PR TITLE
Add html card view

### PR DESCRIPTION
**Pull request by mcw0933**
Hook up jquery and handlebars
    Write card data to json in external file
    Define css for card structure, theme colors
    Provide item-based or all cards view options
    Wire up item view to item/slot icon right-click
    Build card data json from card CSV
    Pull in icon glyphs from Jayce's files, rename to match Cards.csv data
    Ignore card quality plus/minus
    Attempt making .hb files load remotely instead of being embedded in HTML (still needs work)

### CODE REVIEW

**Comment by mcw0933** [comment]
Hey man, finally got something seriously worth looking at for the HTML card view.  It's wired in to item/slot right-clicks, and there's also a view all menu item.

My JavaFX window code sucks, I can't quite get the web browser to size/scroll well.  But if you launch it in the UI first you can then just open cardview.html locally and see it in all it's glory.

I have to say I am really pleased with the results: 
screen shot 2015-08-27 at 1 41 38 am

I still have some work to do on tweaking the css for certain cards.  Some of the render rules are funky for "action/reaction" cards (Raging Strike, Counterspell).  Also I need to fix spacing for single-effect cards that don't have a midbar (basically every "simple" armor/boost cards).

screen shot 2015-08-27 at 1 40 54 am

Finally, the biggest glaring issue with the html cards is the lack of background gradients / texture behind the card graphics, and the lack of a translucent "metal sheen" image / gradient / effect for the card title.  (oh, and overlay images/icons for the rarity symbols) I'm not the hottest at pure image work but I might be able to come up with something.  Dunno if that's in your wheelhouse?

In order to get the comparison cards to appear, since I couldn't get it from savecardart (as you noticed :) Instead I pulled everything from the wiki using a web spider / image downloader called DeepVacuum.  I have most every card, pretty sure the missing ones just aren't on the wiki.  I'll send you a zip via forum PM.

**Comment by mcw0933** [comment]
Can I also just say how kickass it is to have a fast, local, CTRL-F-able master card list open in Chrome?  woo :)

**Comment by RyanHilbert** [comment]
Oh wow, this is great! I guess that answers my forum question, too. It's
not my specialty either, but I could probably manage to crop the rarity
icons out of the cards. I'll be really busy for the next couple of days,
though.

But yeah, really awesome stuff; looking forward to seeing it in action.

**Comment by RyanHilbert** [comment]
I really want to check this out and merge it, but git is being difficult again. I'll try again later tonight.

**Comment by mcw0933** [comment]
Glad you like it.  :)  Which forum question - about how to get the card art?  Yeah, I have no idea why the command isn't working anymore but that wasn't really gonna fly anyway because it requires each card name.  I wasn't going to write a browser script to run the list and pull 'em out that way... (ok, well maybe I would have, barring the wiki :)

If you can grab out the rarity icons, I'm going to try to produce the backgrounds by sampling/masking around a bunch of cards that have a lot of transparency.  I'll probably end up with a background that has a hole in the middle, but hey, ya won't see it anyhow, by definition :)

I may be able to produce a "metal sheen" transparent .png overlay the same way.  Time to roll up my sleeves and fire up Paint.NET.

Finally - what would be really helpful is, if you find any very specific card errors, add them to issue #17 and cite the card that's problematic.

**Comment by mcw0933** [comment]
Oh, sweet - there's a raw background in here: Ogre Gauntlets

**Comment by mcw0933** [comment]
eeeh... nevermind, I'd still need to subtract out the hourglass.  :/

**Comment by mcw0933** [comment]
Got some of the backgrounds going... still need to make the alignment tweaks...
image

**Comment by mcw0933** [comment]
Ahh... muuuuuch nicer :)  Doesn't have the random phantom bottom left icon box on Raging Strike though.  Meh, feature.  :)

image

**Comment by mcw0933** [comment]
I found some pretty decent metal textures I might use to try to make the card titles shiny.  Other than that, I need to clean up some of the artifacts in [the](https://github.com/Xayrn/CardHunterUtils/blob/t_htmlCardView/src/images/AttackBackground.png) [background](https://github.com/Xayrn/CardHunterUtils/blob/t_htmlCardView/src/images/BlockBackground.png) [images](https://github.com/Xayrn/CardHunterUtils/blob/t_htmlCardView/src/images/BoostBackground.png), etc.  Try and tackle that tomorrow.

**Comment by mcw0933** [comment]
Hey - I found and fixed a bug with right-click, where it was interfering/competing with the filter/sort click logic.  Not sure it's the best approach, but it's short and sweet and works.  Lemme know what you think.  I'd also like some feedback on how I did the app singleton for keeping track of global state.

**Comment by mcw0933** [comment]
OMG thank you universe for http://garamond.org

screen shot 2015-08-30 at 7 11 04 pm

**Comment by mcw0933** [comment]
Now with pretty title backgrounds and rarity icons.  :)
capture

Also - this was taken with GaramondNo8 on a Win7 PC - doesn't look _quite_ as good font wise as on my Mac, but hey, what else is new.  :)

**Comment by mcw0933** [comment]
At this point, I think the only really significant thing left that I want to do with this is nice up the in-app CardViewer to not be quite so crappy of a window.  Oh, and I guess try to put in the overlap/rollover thing, too.

**Comment by mcw0933** [comment]
Ok - improved ModalDialog is in.  I'm going to defer the overlap/rollover thing as a future issue.

**Pull request merged**
